const AgeGroupEnum = [
  "tk",
  "k",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
];
const CourseTagEnum = [
  "friendship",
  "sharing",
  "siblings",
  "i am me",
  "feelings",
  "fair play",
  "ive got a problem",
  "overcoming struggle",
  "grown ups",
  "navigating life changes",
  "growing up",
  "disappointment and failure",
  "family strucutes",
  "love",
  "loss and death",
  "emotional expression",
  "asking for help",
  "a walk in their shoes",
  "puberty",
  "identity",
  "bullying",
  "respecting diversity",
  "acceptance",
  "conflict management",
  "goal setting",
  "social media",
  "online safety",
  "sexuality",
  "relationships",
  "i can do it",
  "organizing and planning",
  "reflection",
  "problem solving",
  "stress",
  "healthy choices",
  "ethical decision making",
  "substance use",
  "consent",
  "digital identities",
  "life after highschool",
  "biology",
  "physiology",
  "sexual health",
];

const SelDomainEnum = [
  "Self Awareness",
  "Self Management",
  "Responsible Decision Making",
  "Relationship Skills",
  "Social Awareness",
];

module.exports = { AgeGroupEnum, CourseTagEnum, SelDomainEnum };
